// <auto-generated />
using System;
using CourseInside.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseInside.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250103183659_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseInside.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Category A",
                            Description = "Description for Course 1",
                            Price = 110m,
                            Title = "Course 1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Category A",
                            Description = "Description for Course 2",
                            Price = 120m,
                            Title = "Course 2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Category A",
                            Description = "Description for Course 3",
                            Price = 130m,
                            Title = "Course 3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Category A",
                            Description = "Description for Course 4",
                            Price = 140m,
                            Title = "Course 4"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Category A",
                            Description = "Description for Course 5",
                            Price = 150m,
                            Title = "Course 5"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Category A",
                            Description = "Description for Course 6",
                            Price = 160m,
                            Title = "Course 6"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Category A",
                            Description = "Description for Course 7",
                            Price = 170m,
                            Title = "Course 7"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Category A",
                            Description = "Description for Course 8",
                            Price = 180m,
                            Title = "Course 8"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Category A",
                            Description = "Description for Course 9",
                            Price = 190m,
                            Title = "Course 9"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Category A",
                            Description = "Description for Course 10",
                            Price = 200m,
                            Title = "Course 10"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Category A",
                            Description = "Description for Course 11",
                            Price = 210m,
                            Title = "Course 11"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Category A",
                            Description = "Description for Course 12",
                            Price = 220m,
                            Title = "Course 12"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Category A",
                            Description = "Description for Course 13",
                            Price = 230m,
                            Title = "Course 13"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Category A",
                            Description = "Description for Course 14",
                            Price = 240m,
                            Title = "Course 14"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Category A",
                            Description = "Description for Course 15",
                            Price = 250m,
                            Title = "Course 15"
                        });
                });

            modelBuilder.Entity("CourseInside.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(865),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(879),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(892),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(893),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(895),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(897),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(898),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 8,
                            OrderDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(900),
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("CourseInside.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 110m,
                            OrderId = 1,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1332),
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 120m,
                            OrderId = 2,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1335),
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 130m,
                            OrderId = 3,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1337),
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 140m,
                            OrderId = 4,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1347),
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 150m,
                            OrderId = 5,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1350),
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 160m,
                            OrderId = 6,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1353),
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 170m,
                            OrderId = 7,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1363),
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 180m,
                            OrderId = 8,
                            PaymentDate = new DateTime(2025, 1, 3, 18, 36, 59, 319, DateTimeKind.Utc).AddTicks(1367),
                            PaymentStatus = "Completed"
                        });
                });

            modelBuilder.Entity("CourseInside.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57ba062a-4643-4cb1-b9ef-2a31d6a7f345",
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Admin User",
                            PasswordHash = "AQAAAAIAAYagAAAAENJT3iXuiG79WgV8TbAoTCCg47KfL3cmtygA9Yrj+1Upes64Juj/eTK0urRpurAXzQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "45dcf3bf-c2f8-482f-8622-ae74bc04aea1",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20d6b4e0-2d7a-41dd-b7df-c72d892c9c35",
                            Email = "teacher@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Teacher User",
                            PasswordHash = "AQAAAAIAAYagAAAAEKlG1HiLVDD4Sp0RHTxXmAT6rav5Bc2cqbQ9K+ri6vrHPloOZRRxLE27KJ9O0yaKJQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "53a957bc-f663-4905-861f-f8a6817de763",
                            TwoFactorEnabled = false,
                            UserName = "teacher@example.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5ac3cd7-9c97-4e92-8dc2-cad1122ebb33",
                            Email = "user@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Regular User",
                            PasswordHash = "AQAAAAIAAYagAAAAEMHnYu/mcztFwsazOF/5wtUmovvo4xGu8OgKoChc2rNBXl0vtLz5WRthFHptMyHcRA==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "74d452f1-c370-48ad-9d1d-aea96d74c15d",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CourseInside.Models.Order", b =>
                {
                    b.HasOne("CourseInside.Models.Course", "Course")
                        .WithMany("Orders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseInside.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseInside.Models.Payment", b =>
                {
                    b.HasOne("CourseInside.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("CourseInside.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CourseInside.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CourseInside.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseInside.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CourseInside.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseInside.Models.Course", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CourseInside.Models.Order", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("CourseInside.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
